style: Remove trailing whitespace
reportportal/kubernetes pull request #146
Opened 2020-10-16 20:21 UTC by sijis

Just a little tidying up.

2020-11-15 12:09 UTC, vutny reviewed
Good stuff. It is always annoying, when editing or changing doc/YAML layout, to handle all those completely unnecessary spaces.
Although, the changes become out of sync with `master` by now.

2021-03-04 21:32 UTC, sijis commented
Rebased the PR.

2021-06-11 16:46 UTC, sijis commented
Rebased again.

2021-06-11 16:47 UTC, sijis commented
@waynesun09 if you could review this PR that would also be appreciated.

2021-07-05 11:07 UTC, HardNorth requested changes

2021-07-05 11:07 UTC, HardNorth commented on reportportal/README.md
> -
Why do you remove these lines? Or it's just outdated branch?

2021-07-14 19:12 UTC, HardNorth commented
@sijis Last time rebase please.

2021-07-26 08:51 UTC, merged