Support using existing secrets with cloud services
reportportal/kubernetes pull request #160
Opened 2021-02-24 18:19 UTC by FalconerTC

Right now, supplying `postgresql.endpoint.cloudservice` requires the postgres password to be from values instead of supporting K8s secrets. Using cloudservice shouldn't prevent you from being able to use k8s secrets to store the credentials. This follows conventions seen often in other charts. The same applies to rabbitmq.

These changes are not breaking and we are currently deploying with them

2021-07-14 19:54 UTC, HardNorth commented
@FalconerTC Thank you for the patch! I agree with your point. But I need to double check the patch to ensure nothing left unpatched, especially in new deployments. I'll do that after my current vacation (after July 25th).

2021-07-14 20:50 UTC, HardNorth requested changes

2021-07-14 20:50 UTC, HardNorth commented on reportportal/templates/analyzer-statefulset.yaml
> -        {{ if .Values.rabbitmq.endpoint.cloudservice }}
Could you please also delete this flag from `values.yaml`?

2021-07-14 20:50 UTC, HardNorth commented on reportportal/templates/api-deployment.yaml
> -        {{ if .Values.postgresql.endpoint.cloudservice }}
And delete this one too?

2021-07-22 23:28 UTC, FalconerTC commented on reportportal/templates/api-deployment.yaml
> -        {{ if .Values.postgresql.endpoint.cloudservice }}
@HardNorth Any chance for a re-review?

2021-07-26 09:03 UTC, HardNorth commented on reportportal/templates/api-deployment.yaml
> -        {{ if .Values.postgresql.endpoint.cloudservice }}
@FalconerTC please resolve conflicts

2021-07-28 09:10 UTC, HardNorth commented
@FalconerTC ping

2021-08-02 09:07 UTC, HardNorth approved these changes

2021-08-02 09:08 UTC, merged