Add github action to create helm chart index
reportportal/kubernetes pull request #161
Opened 2021-04-15 17:35 UTC by mhumeSF

Add github action to create helm chart index and host reportportal at
reportportal.github.io/kubernetes. A `gh-pages` branch would need to be
created to publish to.

2021-07-01 17:44 UTC, patsevanton commented
Please review!

2021-07-14 18:20 UTC, eric-engberg commented
Can someone please review this?  It would be nice to have a helm repo to use since the 'stable' repo has been deprecated.

2021-07-14 19:58 UTC, HardNorth commented
@patsevanton @eric-engberg will do this after my current vacation (after July 25th).

2021-07-14 20:07 UTC, HardNorth requested changes

2021-07-14 20:07 UTC, HardNorth commented on .github/workflows/release.yaml
> +      - name: Configure Git
Please use [git credentials configuration action](https://github.com/marketplace/actions/configure-git-credentials), e.g. as here: https://github.com/reportportal/client-java/blob/develop/.github/workflows/release.yml#L57

2021-07-14 20:07 UTC, HardNorth commented on .github/workflows/release.yaml
> +        uses: helm/chart-releaser-action@v1.1.0
Please update to the latest version (v1.2.1)

2021-07-14 20:09 UTC, HardNorth commented
These are only preliminary comments, I need to test the pipeline after vacation.

2021-07-14 20:58 UTC, mhumeSF commented
@HardNorth Thank you for taking the time while on vacation! Look forward to hearing from you when you return.

2021-07-26 11:59 UTC, HardNorth commented
@mhumeSF Sorry, I'm unable to test the action without this fix in `chart-releaser-action`: https://github.com/helm/chart-releaser-action/pull/83
So, postpone for now.

2021-07-26 12:31 UTC, HardNorth commented
@mhumeSF Tested by direct reference on `main` branch and it looks OK-ish: https://github.com/HardNorth/kubernetes/tree/gh-pages

But I still need a stable action version and establish chart release process with our DevOps.

2021-12-01 12:24 UTC, HardNorth commented
@mhumeSF OK, tired of waiting until the GHA release and pointed everything on specific commit. That shouldn't break anything in case of branch update. So we have a first Helm Chart Release: https://github.com/reportportal/kubernetes/releases/tag/reportportal-5.6.0

The repository is accessible by: https://reportportal.github.io/kubernetes
I also added some documentation provided by @valentynkvasov 

All further releases are going to be made through releaser action. Thanks everyone!

2021-12-01 12:24 UTC, closed without merging