add annotation support for serviceaccounts in helm-chart
reportportal/kubernetes pull request #165
Opened 2021-04-26 07:27 UTC by imdhruva

2021-07-26 13:43 UTC, HardNorth requested changes

2021-07-26 13:43 UTC, HardNorth commented on reportportal/Chart.yaml
> +version: 5.3.6
Please update the PR.

2021-07-28 11:11 UTC, kartik-moolya commented
@imdhruva  just a question, have you tried this with IAM role for service Account? (Im assuming you need annotations to service account for that reason) If yes, could you please share a dummy `values.yaml` that you used

2021-08-02 09:50 UTC, HardNorth commented
@imdhruva Ping

2021-08-03 13:22 UTC, HardNorth commented
Merge in: https://github.com/reportportal/kubernetes/pull/187

2021-08-03 13:22 UTC, closed without merging