Release 5.5.0
reportportal/kubernetes pull request #188
Opened 2021-08-04 14:45 UTC by Cyberglamdring

2021-08-04 15:03 UTC, HardNorth commented
@Cyberglamdring Metrics-gathering?

2021-08-06 10:16 UTC, Cyberglamdring commented
Metrics Gatherer tested on Alpha

2021-08-06 10:25 UTC, HardNorth requested changes

2021-08-06 10:25 UTC, HardNorth commented on reportportal/templates/metrics-gatherer-deployment.yaml
> +         {{ if .Values.postgresql.SecretName }}
Please use `{{- ` just to not add empty lines in the result file.

2021-08-06 10:25 UTC, HardNorth commented on reportportal/templates/metrics-gatherer-deployment.yaml
> +{{- end }}
Newline

2021-08-06 10:25 UTC, HardNorth commented on reportportal/templates/metrics-gatherer-service.yaml
> +  type: ClusterIP
Newline

2021-08-06 11:16 UTC, HardNorth requested changes

2021-08-06 11:16 UTC, HardNorth commented on reportportal/templates/metrics-gatherer-deployment.yaml
> +        {{ else }}
Please put `{{- ` here too.

2021-08-06 11:56 UTC, HardNorth approved these changes

2021-08-06 12:59 UTC, pbortnik approved these changes

2021-08-06 12:59 UTC, merged